[package]
name = "snekdown"
version = "0.2.1"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
description = "A parser for the custom snekdown markdown syntax"
homepage = "https://github.com/Trivernis/snekdown"

[lib]
name = "snekdown"
crate-type = ["lib"]

[[bin]]
name = "snekdown"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.7.2"
structopt = "0.3.14"
termion = "1.5.5"
minify = "1.1.1"
htmlescape = "0.3.1"
syntect = "4.2.0"
rayon = "1.3.0"